### ISSUE TITLE
Incorrect top padding on left and right nav

### ISSUE THREAD

**Issue by infojam** [infojam/alfama#6]
Carbon
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1633224/174247868-b3a8b76b-e036-49a7-b29b-81f5dfd7b735.png">

Figma
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1633224/174247893-d9630245-d479-49f4-a173-e8af71884ef1.png">

**Comment by infojamjames** [comment]
Correctly padded and added new sub menu, sub menu items and added links
